import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import BackgroundImage from "@/public/images/dust-background.jpg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const segoeUi = localFont({
  src: [
    {
      path: "../public/fonts/segoe-ui/segoeuithis.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/segoe-ui/segoeuithibd.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-segoe-ui",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className="h-full">
        <div
          className="fixed inset-0 -z-10 bg-cover bg-center h-full"
          style={{
            backgroundImage: `url(${BackgroundImage.src})`,
            filter: "blur(8px)",
            transform: "scale(1.05)",
          }}
        />

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <main className="h-full">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
